### ISSUE TITLE
No list of players

### ISSUE THREAD

**Issue by marek-ganko** [szubersk/poker_stats#1]
Application demands to pass parameter with players nickname but it doesn't give the possibility to list existing hero players in the database.

**Comment by szubersk** [comment]
@marek-ganko 

Indeed. The cost of parsing all hands just to retrieve players' nicknames is too high. Reports are usually run by player who know their nicknames. This won't be implemented unless it's a part of module for opponent analysis.

**Comment by marek-ganko** [comment]
Maybe then better option would be to assume that "our" player is a HERO player. 
In that case it doesn't matter what login does he have, right?

**Comment by szubersk** [comment]
@marek-ganko 

that's why passing Hero nickname is mandatory - to select a player to run the report for.
